
  - name: start nginx
    ansible.builtin.service:
        name: nginx
        state: started
    when: ansible_facts['os_family'] == "Debian" 

  - name: start httpd
    ansible.builtin.service:
      name: httpd
      state: started 
    when: ansible_facts['os_family'] == "CentOS"
