- name: Template a file to /etc/nginx/sites-available/default
      ansible.builtin.template:
        src: /files/default.j2
        dest: /etc/nginx/sites-available/default
        owner: ubuntu
        group: ubuntu
      become: yes
